### ISSUE TITLE
Walking through code doesn't always work as expected.

### ISSUE THREAD

**Issue by Axe319** [christopherroyshields/language-br#5]
Basically the title. "Whole word only" mode which should be activated by walking from a single cursor position also catches string variables with identical names. For example `RawMat` also catches `RawMat$`. The problem lies in line 562 `selection = '\\b' + selection + '\\b';` since regex treats the `$` as a word border character.

**Comment by christopherroyshields** [comment]
I think your saying that in this case you don't want it to consider `$` a word character.  Is that correct?

**Comment by christopherroyshields** [comment]
This should be resolved in the master branch.  Try it out and let me know.

**Comment by Axe319** [comment]
Will do. I will let you know when I get in to work.
